### PR TITLE
feat: vue extractor

### PR DESCRIPTION
**Pull request by cyyynthia**
Implementation of the Vue extractor (that hopefully works!). Also includes some refactoring and some minor fixes related to Windows.

Extraction of `t` function calls have been moved to a shared machine to reduce duplicated code across the React, Svelte, and Vue extractor.

The TextMate grammar for Vue has been slightly tweaked compared to the stock version to allow proper tokenization of `v-bind:` and similar attributes and the inner JavaScript. Grammar have also been tweaked to make Vue interpolations be correctly recognized. This allows for an accurate extraction and support for things such as `<p :aria-label="$t('myKey')">`.

Due to the *experimental* nature of my changes to the TextMate grammar file, and the complexity of the SFC file when it comes to making sense of it, it'd be preferable to try the extractor on a real-world scenario instead of the highly synthetic tests performed in the unit tests. I've seen many edge cases show up and they've been quite challenging to overcome, and I'm unsure if the current implementation does cover everything and there's not a bunch of very subtle bugs and quirks not accounted for.

### CODE REVIEW

**Comment by JanCizmar** [comment]
Good job!

**Comment by cyyynthia** [comment]
According to initial feedback, the extractor is capable of making sense of Vue SFC files. https://github.com/tolgee/tolgee-cli/issues/2#issuecomment-1692935979

Points raised about extraction in plain `.ts` file for composables have been addressed and usage of `useTranslate` is more thoroughly checked.

The thread also mentioned concerns about other ways of using `t` (via `useTolgee` for example) as well as general feedback around cases where `t` might be undetected; While valid and deserving attention, they affect all extractors currently and deserves its own PR. This PR focuses on having a working extractor that behaves like the React or Svelte extractor.

**Comment by stepan662** [comment]
I've checked the code and it looks fine, although quite complex. Vue is especially complex with the multiple ways how to do stuff. I've tested the code on our testapp and I found an issue with this file:

```vue
<template>
  <div v-if="isLoading">Loading namespace...</div>
  <div v-else class="tiles namespaces">
    <div>
      <h1>t function with namespace</h1>
      <div>{{ t('this_is_a_key') }}</div>
    </div>

    <div>
      <h1>t function with default namespace</h1>
      <div>{{ t('this_is_a_key', { ns: '' }) }}</div>
    </div>

    <div>
      <h1>T component with namespace</h1>
      <div>
        <T keyName="this_is_a_key" ns="namespaced" />
      </div>
    </div>
  </div>
</template>

<script setup>
import { useTranslate, T } from '@tolgee/vue';
const { t, isLoading } = useTranslate('namespaced');
</script>
```

It detects only this line `<T keyName="this_is_a_key" ns="namespaced" />`. I guess it expects the global `$t` function, this is an alternative approach which works similarly to the react hook approach.


Also with this [file](https://github.com/tolgee/vue-example/blob/main/src/TranslationMethods.vue) it gets somehow confused and lists 'value' of parameter instead of key:

```
10 keys found in ../tolgee-js/testapps/vue/src/TranslationMethods.vue:
        line 13: this_key_does_not_exist
                default: This is default
        line 20: this_is_a_key
        line 27: this_is_a_key_with_params
        line 37: this_is_a_key_with_params
        line 47: this_is_a_key
        line 54: this_is_a_key_with_params
        line 61: this_is_a_key
        line 67: this_key_does_not_exist
                default: This is default
        line 75: value
        line 87: value
```

Otherwise great job, vue is a challange 😄

**Comment by cyyynthia** [comment]
> I've checked the code and it looks fine, although quite complex. Vue is especially complex with the multiple ways how to do stuff. I've tested the code on our testapp and I found an issue with this file:

Hm, this example should be working, I do have checks for the composable, and the order shouldn't be a problem since the multi-stage approach I took is aimed at re-ordering the bits I need before processing them; I'll give a check to what's going on.

> Also with this [file](https://github.com/tolgee/vue-example/blob/main/src/TranslationMethods.vue) it gets somehow confused and lists 'value' of parameter instead of key:

That's a good catch! I believe I have tests to check for these cases, but I guess I forgot some cases where the confusion can arise for the parser. I'll also add test cases for that.

> Otherwise great job, vue is a challange

To be fair, the only annoying part was getting the TextMate grammar to work (it really expects additional intel from the language server for editors to parse properly) and re-ordering the file. Once that's done, it ain't much harder than for the other parsers 😄

**Comment by cyyynthia** [comment]
@stepan662 Both problems should be fixed; I also tweaked the grammar file and decoder to support nested templates (they behave similar to React.Fragment under certain criterias).

**Comment by paulwer** [comment]
@cyyynthia I also tested this with our project. Works great for us.

Thanks for the work so far❤️

**Review by stepan662 — APPROVED** [review]

**Pull request merged**
